- cloudvolume/__init__.py
Needed to export secrets from the package in __init__
Resolves #23
> fix: missing module secrets

- cloudvolume/cloudvolume.py
- cloudvolume/storage.py
- cloudvolume/threaded_queue.py
- test/test_threadedqueue.py
```
CloudVolume(..., progress=True) # Shows progress bars
Storage(..., progress=True) # shows progress bars
```
ThreadedQueue now checks every 0.1 seconds for exceptions and updates
a progress indicator. Storage now takes advantage of this for
multithreaded uploads and downloads. CloudVolume now supports a
vol.progress flag that switches tqdm output on and off, default False.
Updated some comments for Storage as well.
Resolves #20
> feat: progress flag for CloudVolume, Storage

- .travis.yml
- README.md
- cloudvolume/__init__.py
- cloudvolume/cloudvolume.py
- cloudvolume/lib.py
- cloudvolume/secrets.py
- cloudvolume/storage.py
- test/layer_harness.py
- test/test_cloudvolume.py
- test/test_connectionpools.py
- test/test_provenance.py
- test/test_storage.py
You can now set cache=True to enable reading from disk after downloading.
This is only recommended for jobs less than a few gigabytes, large jobs
will fill up your disk.
Cache location: `$HOME/.neuroglancer/cache/$PROTOCOL/$BUCKET/$DATASET/$LAYER/$RESOLUTION`
You can flush the cache your object is referring to with `vol.flush_cache()` and globally with `rm -r $HOME/.neuroglancer/cache/`
Note: Doesn't support Boss protocol yet. That's more complicated.
Resolves #10
> feat: added cache flag to CloudVolume

- requirements.txt
- test/test_storage.py
Google introduced a bug into google-resumable-media 0.3.0 where they checked the checksum of the gzipped file and compared it with the uncompressed version. Reverted to 0.2.3 in the meantime while they fix it. 
https://stackoverflow.com/questions/46804668/gcs-datacorruption-checksum-mismatch-while-downloading
> Fix DataCorruption Error

- cloudvolume/cloudvolume.py
- test/test_cloudvolume.py
The caching logic would crash trying to compress `None` objects.
```
vol = CloudVolume("gs://neuroglancer/drosophila_sergiy/dummy_mask", cache=True, bounded=False, fill_missing=True)                                                                                                                                                    
vol.flush_cache()
print vol[0:5,0:5,0:5]  
Traceback (most recent call last):
File "test.py", line 37, in <module>
print vol[0:5,0:5,0:5]                                                                                                                                                                                                                                                
File "/Users/wms/cloud-volume/cloudvolume/cloudvolume.py", line 736, in __getitem__
cutout …
```
> fix: cache + fill_missing interaction crash

- cloudvolume/connectionpools.py
- cloudvolume/storage.py
- test/test_connectionpools.py
We never use clients other than to get buckets. For a dataset
where we were doing multiprocessing, the gcloud buckets were
stalling out threads. It took a while to find out why.
> fix: pool on buckets instead of clients for gcloud

- cloudvolume/cloudvolume.py
- cloudvolume/lib.py
- test/test_cloudvolume.py
- test/test_lib.py
Only allocate as much memory as the final cutout requires.
Resolves #75
> Reduce Memory Usage for Non-Aligned Downloads

- cloudvolume/storage.py
This is necessary to use storage with multiprocessing.
Imported from the parallel download branch. Requested by @sdorkenw to use storage independently.
> fix: added reset_connection_pools to storage.py

- cloudvolume/sharedmemory.py
- cloudvolume/txrx.py
- test/test_sharedmemory.py
There were errors associated with shared memory allocation.
1) ValueError: The name is too long 
OSX supports only smaller shared memory names (~25 characters?) and doesn't fit the UUID I was using.
2)  ValueError: The size is invalid or the memory is read-only
I couldn't find good documentation of how that system works. OS X also doesn't have easily viewable shared memory allocations like linux does at /dev/shm. Therefore, I emulated shared memory via files.
Linux will still use real shared memory. This is mainly so I can run pytest in peace.
> feat: shared memory emulation using the filesystem for OSX

- .gitignore
- cloudvolume/chunks.py
- cloudvolume/cloudvolume.py
- cloudvolume/compressed_segmentation.py
- cloudvolume/compression.py
- cloudvolume/txrx.py
- test/test_cloudvolume.py
compressed_segmentation is a format invented by JBMS for use with neuroglancer. It takes labels e.g. uint64s and renumbers the voxels inside to smaller numbers so that storage takes less space while affording random access. In tests, it typically comes out smaller than merely gzipped segmentation.
https://github.com/google/neuroglancer/tree/master/src/neuroglancer/sliceview/compressed_segmentation
This PR introduces to CloudVolume a pure python encoder/decoder by Yann Leprince at HBP.
https://github.com/HumanBrainProject/neuroglancer-scripts/blob/master/src/neuroglancer_scripts/_compressed_segmentation.py
There is a C++ version due to Stephen Plaza at Janelia that might be worth integrating with Cython here: https://github.com/janelia-flyem/compressedseg
> Python Compressed Segmentation Codec

- ChangeLog
- cloudvolume/sharedmemory.py
- cloudvolume/txrx.py
- test/test_cloudvolume.py
- test/test_sharedmemory.py
Currently paralellizes the aligned uploads for both ordinary and non-aligned uploads. 
Painting the non-aligned shell is currently handled by a single process.
The code does not yet handle low memory situations.
Resolves #77
> feat: parallel uploads

- ChangeLog
- cloudvolume/chunks.py
- cloudvolume/sharedmemory.py
- cloudvolume/txrx.py
- cloudvolume/volumecutout.py
This matches the underlying data in the cloud and how Julia and other languages interfacing with CV expects it anyway.
> perf: use fortran order internally in numpy arrays

- cloudvolume/cloudvolume.py
- cloudvolume/sharedmemory.py
- cloudvolume/txrx.py
- test/test_cloudvolume.py
- test/test_sharedmemory.py
Adds the ability to upload from shared memory. The comment says it best:
```  
def upload_from_shared_memory(self, location, bbox, cutout_bbox=None):
"""
Upload from a shared memory array. 
MEMORY LIFECYCLE WARNING: You are responsible for managing the lifecycle of the 
shared memory. CloudVolume will merely read from it, it will not unlink the 
memory automatically. To fully clear the shared memory you must unlink the 
location and close any mmap file handles. You can use `cloudvolume.sharedmemory.unlink(...)`
to help you unlink the shared memory file.
EXPERT MODE WARNING: If you aren't sure you need this function (e.g. to relieve 
memory pressure or improve performance in some way) you should use the ordinary 
upload method of vol[:] = img. A typical use case it transferring arrays …
```
> feat: upload from shared memory

- ChangeLog
- cloudvolume/connectionpools.py
- cloudvolume/secrets.py
- cloudvolume/storage.py
- test/test_connectionpools.py
To use, add a secret prefixed with the name of the bucket and a hyphen.
E.g. if your bucket is mybucket, your secret name would be
`mybucket-google-secret.json` or `mybucket-aws-secret.json`.
The logic will default to `google-secret.json` or `aws-secret.json`
if there is no specific bucket secret.
NEW: If no secret is provided at all, use default application credentials
for Google.
Resolves #105 and partially #35
It's easy to implement for AWS, but I'm not set up to test it.
> feat: supporting bucket specific secrets for aws and google

- ChangeLog
- cloudvolume/txrx.py
- requirements.txt
multiprocessing.Pool has a longstanding known bug where
childprocesses abruptly dying results in indefinite hanging.
This can happen e.g. if a child process exceeds the memory
limit and is killed by the OS violently.
As of Python 3.3, concurrent.futures.ProcessPoolExecutor should
raise a concurrent.futures.process.BrokenProcessPool under those
conditions.
https://docs.python.org/3/library/concurrent.futures.html
> fix: use concurrent.futures.ProcessPoolExecutor vs mp.Pool

- cloudvolume/txrx.py
Previously, I was very conservative and wanted to ensure
that the usage of shared memory was completely invisible
to the end user of downloaded numpy arrays. However, this
required making a copy resulting in 2x memory usage.
I conducted some experiments showing that we can safely
avoid making this copy. Instead, we merely unlink the
shared memory. The memory region will remain accessible
so long as there is an open file descriptor to it. The FD
will be closed when the output VolumeCutout is garbage collected.
In all common use cases I have witnessed, this should result in
the transparent usage of shared memory without the concomitant
memory cost. In the case that a user fills an array with
thousands of VolumeCutouts, they have the option of making a
copy using np.copy and closing the file …
> perf: 1x memory usage for parallel downloads

- README.md
- cloudvolume/__init__.py
- cloudvolume/cloudvolume.py
- cloudvolume/lib.py
- cloudvolume/skeletonservice.py
- requirements.txt
- test/test_skeletons.py
**Neuroglancer Skeleton Format**
Filename: `$CLOUDPATH/skeletons/$SEGID`  
| Vertex Count (Nv) |  Edges Count (Ne)  |  Vertices           |  Edges         | 
|-------------------|--------------------|---------------------|----------------| 
| uint32            |  uint32            |  Nv x XYZ float32s  |  Ne x 2 uint32 | 
| 4 bytes          |  4 bytes          | Nv x 12 bytes          |  Ne x 8 bytes  |
> feat: vol.skeleton for accessing Neuroglancer skeletons

- requirements.txt
> chore: upgrade tenacity to 4.10.0 for python 3.7 compatibility

- requirements.txt
See https://pypi.org/project/google-cloud/
Should get rid off all those related, confusing error messages:
>google-cloud-logging 1.4.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.3.0 which is incompatible.
google-cloud-speech 0.30.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.3.0 which is incompatible.
google-cloud-dns 0.28.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.3.0 which is incompatible.
google-cloud-vision 0.29.0 has requirement google-api-core<0.2.0dev,>=0.1.0, but you'll have google-api-core 1.3.0 which is incompatible.
google-cloud-bigquery 0.28.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.3.0 which is incompatible. …
> chore(requirements.txt): replace deprecated google-cloud with google-cloud-storage

- AUTHORS
- ChangeLog
- README.md
- cloudvolume/__init__.py
- cloudvolume/cacheservice.py
- cloudvolume/cloudvolume.py
- cloudvolume/txrx.py
- test/test_cloudvolume.py
@wongwill86 wanted faster cache access on disk which required
disabling cache compression independent of how we treat the
storage endpoint (where we'd like it compressed).
Resolves #130
> feat: independent control of cache compression

- README.md
- cloudvolume/cloudvolume.py
- cloudvolume/txrx.py
- test/test_cloudvolume.py
Transfer files from one storage to another while bypassing the
memory intensive painting process. This potentially allows for
the transmission of arbitrary sized volumes given an optimized
implementation of this concept.
TODO: don't decompress/recompress, parallel, don't generate all
filenames up front.
> feat: transfer_to implementation

- cloudvolume/cloudvolume.py
* Adds an argument to the cloud-volume initialization so that users can explicitly specify the desired voxel resolution instead of needing to coordinate with the info file. This performs a quick conversion to mip index within the `__init__` function, so the change should be otherwise invisible. 
All tests still pass aside from `test_boss_download` which I probably just haven't configured on my workstation. If there's an easy way to do this I can re-run the test, but it seems unrelated.
> Specifying mip level by voxel resolution

- cloudvolume/meshservice.py
This changes the API for vol.mesh.save(), replacing the old filename parameter with a filepath parameter that's a full or relative path to the file you want to write (you should now also provide an extension). The old behaviour if you don't provide this parameter is retained.
> vol.mesh.save() refactor path code

- README.md
- cloudvolume/cloudvolume.py
- cloudvolume/skeletonservice.py
- test/test_skeletons.py
This PR adds:
We'll need to handle getting a path from a specified root, but how that works exactly will depend on the use case. It gets weird when multiple components are present.
> feat: cable_length, downsample, improved Consolidation, SWC file support, connected components

- .travis.yml
- cloudvolume/__init__.py
- cloudvolume/cloudvolume.py
- cloudvolume/compression.py
- cloudvolume/exceptions.py
- cloudvolume/txrx.py
- test/test_cloudvolume.py
Relevant to #156 
Also refactors CloudVolumes exceptions into a single exceptions module so they can be more easily referenced.
> fix: transfer_to retains Content-Type and respects existing info.

- cloudvolume/txrx.py
- test/test_cloudvolume.py
Shared memory attempts to mmap a zero size buffer and crashes
if there is no aligned core to the image.
Resolves #164
> fix: multiprocess upload crashes on thin non-aligned images

- cloudvolume/viewer.py
- cloudvolume/volumecutout.py
- Allows reusing the same port number after killing a script
- Allows continuation of the program and multiple uses of the viewer within the same script
- Ensures that the hostname argument actually works
> allow reestablishing viewer server in the same python session

- cloudvolume/skeletonservice.py
- test/test_skeletons.py
Downsampling currently relies on computing a set of paths then striding, however this often causes the destruction of key joints. 
What we'd prefer is if each segment between critical points (terminal and branch nodes) would be downsampled while preserving heads and tails then reunifying that set of paths.
> feat: joint preserving downsample

- cloudvolume/storage.py
We omit a metadata request. This results in 2x less API calls.
> perf: 1.5-2x faster CloudVolume on Google Cloud Storage

- cloudvolume/secrets.py
aws_credentials: likely less mystic error from calling code if no credential is available.
google_credentials: potentially enabling retries in the future
> misc enhancements

- cloudvolume/cloudvolume.py
- cloudvolume/server.py
Potential uses:
1. Compatibility with compressed files on local disk. This especially helps CloudVolume newbies get started really easily (they often write HDF5 to Precomputed on their local disk because they haven't set up cloud storage yet).
2. Allow access to a non-public dataset by handing out cloudvolume keys.
3. Enable aggressive client-side caching of downloaded data.
4. Use C++/Python codecs to translate unviewable formats to neuroglancer readable formats (e.g. kempressed) (superset of 1)
Workflow:
1.
```python
vol = CloudVolume('file:///tmp/removeme/subvol')
vol.view()
>>> Neuroglancer server listening to http://localhost:1337
```
2. `precomputed://http://localhost:1337/subvol`
> feat: neuroglancer compatible link with vol.view()

- cloudvolume/cloudvolume.py
- cloudvolume/exceptions.py
- cloudvolume/lib.py
Download_point can raise a ValueError if the bbox is out of bounds. This PR adds a flag to allow a cropped bbox, and resets self.mip if a ValueError happens.
> Add allow_cropped flag to CloudVolume.download_point

- cloudvolume/cloudvolume.py
- test/test_cloudvolume.py
it seemed that the max= keyword is not correct for replace in python 3..  simply leaving it as a non keyword argument fixes this.  I added a parameterized test to exercise the function that reveals the bug.
> adding test for use_https and fixing replace call

- cloudvolume/cloudvolume.py
- cloudvolume/datasource/graphene/__init__.py
- cloudvolume/datasource/graphene/metadata.py
- cloudvolume/datasource/precomputed/__init__.py
- cloudvolume/paths.py
I think i found the bug related to #247 , the GrapheneMetaDataService needed to allow remapping of https on the data_dir.  Please let me know if this is the correct way to fix this within the plugin architecture.
> fix: added use_https to graphene metadata service

- cloudvolume/datasource/precomputed/skeleton.py
Adds an optional parameter `return_indices` to both methods `path()` and `interjoint_path()`. If `True`, the result will contain the path as vertex indices, rather than vertex coordinates. This allows users to retrieve/restore `radii` and `vertex_type` for each path.
Default value is `False` to maintain backward compatibility.
> feat(PrecomputedSkeleton): optionally return indices for paths

- cloudvolume/storage/storage_interfaces.py
Google Cloud Storage never returns 404s when using use_https, it
always returns 403 (to prevent you from learning that file names
exist).
> fix: treat 403 like 404 for HTTPS interface

- README.md
- cloudvolume/datasource/graphene/mesh.py
- cloudvolume/datasource/graphene/metadata.py
- cloudvolume/frontends/graphene.py
- cloudvolume/secrets.py
* store credentials in file named `chunkedgraph-secret.json`, eg: `{"token":"<auth_token>"}`
* token will be in `auth_header` dictionary in meta class
> feat: support for chunked graph server authentication

- README.md
- cloudvolume/cloudvolume.py
- cloudvolume/datasource/__init__.py
- cloudvolume/datasource/boss/image.py
- cloudvolume/datasource/precomputed/__init__.py
- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/mesh.py
- cloudvolume/datasource/precomputed/metadata.py
- cloudvolume/datasource/precomputed/skeleton/__init__.py
- cloudvolume/datasource/precomputed/skeleton/sharded.py
- cloudvolume/datasource/precomputed/skeleton/unsharded.py
- cloudvolume/exceptions.py
- cloudvolume/frontends/precomputed.py
- cloudvolume/paths.py
- test/test_cloudvolume.py
We were discussing a problem we are having where some of our collaborators have spreadsheets of neuroglancer links, but we are moving the layer they point to into cheaper storage. We are thinking of instrumenting Neuroglancer and CloudVolume with a redirect capability. 
I looked around for HTTP 301 support on GCS, but it didn't seem to exist, so we are proposing to handle redirects like so:
info:
```json
{
... may contain additional keys ... 
"redirect": "precomputed://gs://new/location/"
}
```
The redirect process would abort with an error once a cycle is detected. 
This adds the `max_redirects` flag to CloudVolume so that you can specify how many redirects are allowed. 0 for direct access, 10 by default.
If a redirect occurs, a readonly flag is set on image upload automatically, but can …
> feat: add redirection feature to info files

- cloudvolume/cloudvolume.py
this fixes an issue where the "del" command wasn't actually removing the object from the dictionary
i'm not entirely sure exactly what was going on, but my best guess is that it was related to some namespace issue where `kwargs` was already defined in locals
by passing it through "dict" i believe this does an object copy which then allows del to complete
> fix: actually del cls

- cloudvolume/storage/storage_interfaces.py
On S3 when a user from a separate account puts objects into a S3 bucket that they do not own, the default behavior is that the actual owner of that bucket has no privileges to those objects.  This is in my experience rarely desired behavior and can be quite tedious to fix after the fact.
This PR attempts to set a default ACL for objects created using cloud volume.
This is not generalized and might be necessary for other clouds as well.
Also, would need to be propagated through the code in order for a user to be able to supply a custom ACL, in the case that they actually want ACL to limit owner control.
Happy to to more work on this as needed but wanted to check in first to make sure it was something wanted or if you had some other idea how to tackle this.
> sets ACL by default for s3 interface

- README.md
- cloudvolume/cacheservice.py
- cloudvolume/cloudvolume.py
- cloudvolume/compression.py
- cloudvolume/datasource/boss/__init__.py
- cloudvolume/datasource/graphene/__init__.py
- cloudvolume/datasource/precomputed/__init__.py
- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/image/tx.py
- cloudvolume/datasource/precomputed/skeleton/__init__.py
- cloudvolume/exceptions.py
- cloudvolume/lib.py
- cloudvolume/storage/storage.py
- cloudvolume/storage/storage_interfaces.py
- requirements.txt
- test/test_cloudvolume.py
- test/test_compression.py
- test/test_lib.py
- test/test_storage.py
This adds brotli compression with a default compression level of 6.
My [testing](https://nbviewer.jupyter.org/github/neurodata/boss-export/blob/lambda/scripts/bench_compress.ipynb) has shown that there's a nice 10% compression rate advantage, with a small cost in compression/decompression speed.
I added tests for brotli with localfile volumes, but wasn't able to run the s3/gcs specific tests.
I did test "pulling" one of our brotli compressed datasets from a public precomputed test volume we have which you should be able to test as well.  See below:
```python3
import os
import boto3
import numpy as np
from PIL import Image
from cloudvolume import CloudVolume
path = "s3://open-neurodata-test/ZBrain/ZBrain/ZBB_y385-Cre"
vol = CloudVolume(path)
image = vol[0:512, 0:512, 0:16]
img = …
```
> feat: add brotli compression option

- cloudvolume/storage/storage_interfaces.py
- test/test_storage.py
This PR fixes a missing import for brotli support on the http interface.
Also adds a test depending on neurodata open data bucket (needed to be a brotli dataset).
> fix: missing import for http interface

- cloudvolume/storage/storage_interfaces.py
- requirements.txt
Somehow I missed that `urllib3/requests` does now support `brotli`, through the optional install parameter in urllib3 (and by using latest releases from both).  Discovered this yesterday when I had a different version of requests installed in a different virtual environment and was running into problem decoding brotli encoded data (because it was trying to decode an already decoded response, and I had brotli installed in that environment).
A few things to keep an eye out for w/ this PR:
1. This "unpins" and upgrades `urlib3`.  Also upgrades requests, but that wasn't unpinned, so don't think it's a big deal.  Not sure if pinning urlib3 was important, can repin if necessary.  Brotli was added in 1.25 of urlib3.  I tested on 1.25.7.  Requests added support in latest release, 2.22.0.
2. I'm …
> install: requests/urllib supports brotli

- cloudvolume/datasource/precomputed/sharding.py
- requirements.txt
With default settings assuming 9 bits for each in the spec:
Shard index cache will take up about 4MB (512 entries)
Minishard index cache will take up potentially more... (128 entries) It is a bit less useful than the shard index cache, but for example, I ran across a wild example of a spec with 0 shard bits and many repeated accesses to the same minishards. A small cache will speed up odd cases like this.
Introduces new dependency on `lru-dict`
Partially addresses #264
> perf: cache shard and minishard indices

- test/test_threadedqueue.py
should address a deprecation warning
> changing spelling of isAlive>is_alive

- cloudvolume/frontends/precomputed.py
This will provide numpy compatibility, and in turn Dask comaptibility.
Resolves #304
> redesign: cv.shape returns a tuple + cv.ndim (BREAKING)

- cloudvolume/datasource/graphene/mesh.py
- cloudvolume/datasource/graphene/metadata.py
- cloudvolume/datasource/precomputed/mesh/unsharded.py
- cloudvolume/mesh.py
- test/test_graphene.py
The draco_grid_size is necessary for mesh vertex deduplication and differs in each dataset
> Feat: store draco_grid_size in info file

- cloudvolume/dask.py
- test/test_dask.py
I was finding a huge slowdown when opening many volumes for writing on a cloud filesystem.  All the metadata files were being written from my machine -- instead of being sharded to workers.  
In addition, when compute=False, it may not be the intention of the caller to ever write out data.  The PR delays the writing of `info` or `provenance` until compute time.
For these reasons, I think we can delay writing the metadata.  It's an open question to me if we should always wrap in `dask.delayed`, regardless of the value of compute.  I believe this may be better, and am trying to open a discussion with the dask maintainers on a similar PR in their repo - dask/dask#5797
> Delay creating metadata in dask.to_cloudvolume 

- cloudvolume/datasource/graphene/__init__.py
- cloudvolume/datasource/graphene/mesh.py
- cloudvolume/datasource/graphene/metadata.py
- cloudvolume/exceptions.py
- cloudvolume/frontends/graphene.py
- cloudvolume/frontends/precomputed.py
- requirements.txt
- test/test_graphene.py
This PR does two tasks:
1. Support the legacy (1.0) and new (api/v1) style requests to graphene servers.
2. Provide a means for downloading flat segmentation at a given time-point from graphene. 
This is provided by the `agglomerate=True` and `timestamp=XXXX` flags on the `cv.download` method.
The agglomerate flag will work on both api/v1 and 1.0 endpoints, but it will only work practically on the api/v1 endpoints due to the implementation of "get_roots".
> feat: agglomerating entire blocks of proofreading

- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/image/tx.py
- cloudvolume/datasource/precomputed/metadata.py
- cloudvolume/exceptions.py
- test/test_cloudvolume.py
This sets the property "locked" to true in each selected mip within info['scales']. It is then checked when calling upload or delete.
This mechanism is very vulnerable to race conditions, and is mainly intended for an additional safety mechanism to prevent accidental deletion. It's not meant to be called frequently.
> feat: add image write locking per mip level 

- cloudvolume/datasource/precomputed/sharding.py
- cloudvolume/lru.py
- requirements.txt
- test/test_lru.py
Noticed pylru is GPL and am trying to keep CV BSD. This cures the license issue.
I looked around and all the other implementations either are not as convenient for some reason or don't have the right license, so I wrote my own. 
As a bonus, the new `LRU` class includes a `resize(N)` method, so it's easy to customize after the fact without losing your cache.
> refactor: drop pylru for custom version

- cloudvolume/microviewer/__init__.py
- cloudvolume/microviewer/datacube.js
- cloudvolume/microviewer/index.html
This implementation is a little slow right now and includes some duplicated code.
I realized we can avoid using hashes with a double array scheme.
1. renumber data
2. second array size of number of uniques contains original label
However, making this happen requires a slowdown in load time due to array renumbering. We should test a larger volume to see if this is a problem.
> feat(microviewer): add segmentation toggle to plain segmentation

- cloudvolume/datasource/graphene/mesh/sharded.py
- cloudvolume/datasource/graphene/mesh/unsharded.py
Enables `cv.mesh.get` for Graphene sharded meshes. There are two special parameters this PR adds to the `get` function as well.
Ordinarily for Graphene, the `cv.mesh.get` function will contact the PCG server to request a manifest. Since the server, in order to traverse the PyChunkGraph octree to find the child labels with actual meshes, performs a series of `exists` calls, it already does the work of finding the index and minishard index of each shard. It therefore returns the manifest in an atypical fashion: 
```json
{
"fragments": [
"~3/47461891-0.shard:3430219:1073", 
"~3/45385220-0.shard:310763:1182", 
"~3/42020357-0.shard:2270331:304"
],
}
```
Here the tilde means the mesh is an initial sharded mesh, the 3 means layer 3 of the PCG, she middle section is the name of the shard file, …
> feat: download sharded meshes based on mesh manifests

- cloudvolume/paths.py
- test/test_paths.py
To address: [https://github.com/seung-lab/cloud-volume/issues/349](https://github.com/seung-lab/cloud-volume/issues/349), an issue where windows paths were not parsed properly. Specifically, the bucket was getting added to the cloudpath twice.   
I added a simple test to make sure the fix works.
> address issue with windows basepath extraction

- cloudvolume/datasource/precomputed/mesh/multilod.py
- test/test_precomputed_multilod.py
A small fix to produce a useful exception when lod requested is out of range on a ShardedMultiLevelPrecomputedMeshSource.
(@schlegelp on https://github.com/seung-lab/cloud-volume/issues/337)
> Fix LOD out of range error

- cloudvolume/datasource/precomputed/sharding.py
Looks like neuroglancer uses this default. Thanks for reporting @schlegelp! 
Related to #354
> fix: default to 'raw' for shard encodings

- cloudvolume/datasource/precomputed/image/__init__.py
`gpts()` returns grid points in dataset space, need to translate them to create correct cutouts from `img`.
> fix(precomputed): makeshard cutouts relative to provided image

- cloudvolume/chunks.py
Don't exactly understand the operations involved here, but I verified that with the change below a chunk downloaded with CloudVolume and re-uploaded as JPEG shows up at the correct position / in the correct orientation in Neuroglancer. Previously, for my 128x128x16 chunks Neuroglancer would complain about shape 16384x16, instead of the expected 128x2048
> fix(encode_jpeg): Neuroglancer expects vertical tile layout

- cloudvolume/datasource/graphene/mesh/sharded.py
now that CloudFiles is being used, res['filename'] should become res['path']
> Fix: get_meshes_on_bypass

- cloudvolume/datasource/graphene/mesh/sharded.py
- cloudvolume/frontends/graphene.py
- cloudvolume/mesh.py
I have implemented a more elaborate mesh stitching routine for graphene sharded.  It now takes into account the mesh level of each fragment that is downloaded, in order to label the chunk boundaries dynamically on each fragment in a way that scales with the level of the chunk the fragment came from, and then only removes duplicate vertices on those chunk boundaries.
To do so, i did a little refactoring of the deduplication code so i could call it outside of the Mesh class.  Happy to consider refactoring this in some way, and might be duplicating effort that exists elsewhere in pychunkedgraph. 
I've tested that this enables proper mesh stitching of graphene sharded meshes on a proofread ID example from minnie, but haven't tested it on fly.
> adding smart graphene multi-level mesh stitching

- cloudvolume/chunks.py
- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/sharding.py
Shard Write:
* fix: don't crop partially intersecting shards
* feat: Add progress flag to `make_shard`
* perf: Avoid repeated string concatenation
Shard Read:
* perf: Avoid copies when converting JPEG bytes to numpy array
* 30ms -> 0.5ms per call
* perf: Bundle adjacent byte range requests
* 1000 s -> 5 s for completely empty/black shard
* 1 s -> 0.5 s for example in https://github.com/seung-lab/cloud-volume/issues/354
> Image shard generation

- .travis.yml
- README.md
- setup.py
Retain backwards compatibility using the python_requires flag.
See https://github.com/seung-lab/cloud-volume/wiki/Policy
> BREAKING: Drop official support for Python 2.7

- cloudvolume/chunks.py
- requirements.txt
- test/test_chunks.py
simplejpeg uses an updated version of libjpeg-turbo which can be much faster than the version of libjpeg used by Pillow.
> perf: use simplejpeg for JPEG encoding/decoding

- test/test_cv/sharded_info.json
- test/test_graphene.py
I have added some more tests to ensure that mesh access works properly with the newer graphene server protocols.
> test(graphene): add tests for meshes based on real data

- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/image/common.py
- cloudvolume/datasource/precomputed/image/rx.py
- test/test_sharding.py
For shard generation and reading large cutouts, several thousand codes need to be calculated. By allowing the entire array as input, we properly utilize numpy:
```python
grid_size = Vec(520,440,260)
gpts = np.array([np.random.randint(520, size=65536), np.random.randint(440, size=65536), np.random.randint(260, size=65536)]).T
%timeit for gridpoint in gpts: compressed_morton_code(gridpoint, grid_size)
%timeit compressed_morton_code(gpts, grid_size)
> perf(sharding): compressed morton code and gridpoints

- cloudvolume/datasource/graphene/mesh/sharded.py
When doing a bounding box query with graphene, it doesn't make sense to specify something other than level2 because you don't want to get stitched fragments that extend well beyond your bounding box in some inconsistent fashion depending on the state of mesh stitching in the backend. 
This simply sets the level=2 when specifying a bounding box. 
I have a corresponding PR on the PCG backend to make this functional. 
https://github.com/seung-lab/PyChunkedGraph/pull/229
> fixing level=2 for bounding box queries

- cloudvolume/mesh.py
A missing 'import re' prevents Mesh.from_obj() from working.
```
Traceback (most recent call last):
File "obj_to_ngl.py", line 28, in <module>
main()
File "obj_to_ngl.py", line 22, in main
cv_mesh = Mesh.from_obj(text=Path(meshfile).read_text(), segid=mesh_id)
File "/Users/eric/anaconda3/envs/fafb/lib/python3.8/site-packages/cloudvolume/mesh.py", line 258, in from_obj
(v1, v2, v3) = re.match(r'v\s+([-\d\.]+)\s+([-\d\.]+)\s+([-\d\.]+)', line).groups()
NameError: name 're' is not defined
```
> Missing 'import re' in mesh.py.

- cloudvolume/microviewer/__init__.py
- cloudvolume/microviewer/datacube.js
- cloudvolume/volumecutout.py
Resolves #171
It seems that FireFox and Chrome both support BigUint64Arrays now.
It's a little tricky because BigInt and Number do not mix so casting
has to be done carefully.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
> feat(uviewer): support displaying bigint segmentation

- cloudvolume/datasource/boss/image.py
- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/image/rx.py
- cloudvolume/frontends/precomputed.py
This can save 2-4x on memory usage.
```python
lbls, remap = cv.download(cv.bounds, renumber=True)
```
If you download a large volume as a uint64 but it could be represented using a uint16, you can theoretically resize it, but that requires allocating the larger memory structure, allocating more, and then downsizing it. With this approach, you never allocate the larger data type and render the volume in renumbered form.
> feat(image): download an image already renumbered

- cloudvolume/chunks.py
- test/test_chunks.py
Array shape mixup in between the transposing / axis swapping / reshaping transformations.
Happened during the switch to simple_jpeg (#392)
> fix(encode_jpeg): correct 3D->2D shape for Neuroglancer

- README.md
- cloudvolume/datasource/graphene/metadata.py
- cloudvolume/secrets.py
e.g. flywire.dynamicannotationframework.com-cave-secret.json
(fake example)
Also adds the ability to configure the `.cloudvolume` directory via an environment variable `CLOUD_VOLUME_DIR`
Resolves #458
> feat: add cave-secret.json and allow for fqdn qualification

- cloudvolume/datasource/precomputed/mesh/multilod.py
- requirements.txt
DracoPy <= 0.0.15 erroneously assumes that every vertex is a float32, by copying the draco vertex buffers into float arrays. This works with the current `multilod.py` code (in certain platforms) because the multilod code views the DracoPy float data as np.int32, so if the original vertices were also int32 the data is unchanged. DracoPy 0.0.19 fixes this earlier bug, by appropriately converting the vertices into floats if they are of a different type. Ironically that fix means that the multilod code is now broken, because it views the now converted float data as np.int32. Therefore, we should remove this np.view call. Talked with Will and we agreed that this is the appropriate fix, and that the view was likely originally added to get around DracoPy's bug. Additionally, I confirmed that …
> Fix: multilod mesh vertex corruption

- cloudvolume/datasource/precomputed/spatial_index.py
- cloudvolume/lib.py
- test/test_lib.py
Broke the spatial index query during the move to floating point resolution.
This fix changes how xyzrange is implemented to allow floating point steps and also return a clone of the point Vec (which should avoid certain issues anyway). It also makes Vec check for floating point arguments to determine dtype, so this change is technically backwards incompatible though I think few people will notice.
> fix(spatial_index): correct calculation of file paths

- cloudvolume/datasource/precomputed/image/common.py
- test/test_sharding.py
Based on this issue filed in Igneous: https://github.com/seung-lab/igneous/issues/100
> fix(image shard): morton codes not handling single dimensions

- cloudvolume/datasource/precomputed/image/common.py
- test/test_sharding.py
For grid dimensions that are a power of 2, the code was attributing an extra bit.  Fixing that also seems to fix the prior problem of size=1 dimensions (a power of 2!) naturally, without the extra check.
I added a test for the case I recently hit, where the morton code was out of range (195, where the #chunks was 128).  In addition, a prior test was incorrect and updated.
> fix: update morton coding

- cloudvolume/cacheservice.py
- cloudvolume/datasource/graphene/mesh/unsharded.py
Some options exclude caching.
Resolves #493 
Note that sharded meshes are not cached yet, though their manifests are.
> feat: cache graphene manifests

- cloudvolume/dask.py
- test/test_dask.py
I originally made this change before I understood the dask ecosystem, and I was desiring to have many volumes'  created in parallel across many workers.
For other output formats (parquet, zarr, etc), the metadata is written at graph creation time, not delayed to run time.  So this change modifies the behavior to be consistent with the rest of the ecosystem.
> Revert delay of creation of metadata when using dask

- cloudvolume/datasource/precomputed/mesh/multilod.py
- cloudvolume/datasource/precomputed/sharding.py
Hi @SridharJagannathan I was working on implementing multi-res meshes in Igneous. I haven't gotten as far as you or David on producing actual different resolutions, but I did manage to get a single resolution to display. In order to do so, I had to make two changes to CloudVolume that alter the `data_offset` you added to the sharding handler. The changes work, and they seem to conform to the spec, but I wanted to make sure I am not breaking something that is working for you with these changes.
In the Neuroglancer spec, it says that the manifest should be located after the mesh data and implies that the manifest should be the first element accessed. I changed the minishard_index so that the offset points to the beginning of the manifest and the size is the manifest size. …
> fix: adjustments to get multires meshes displaying correctly

- cloudvolume/lib.py
following the convention of python indexing, the `maxpt` should not be inclusive?
according to the measurement of `size` or `length`, it seems that this is true.
if so, the point should not be contained if it is on the coordinate of `maxpt`?
> make contain more accurate for boundary points

- README.md
- cloudvolume/chunks.py
- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/image/common.py
- cloudvolume/datasource/precomputed/image/rx.py
- cloudvolume/frontends/graphene.py
- cloudvolume/frontends/precomputed.py
- cloudvolume/lib.py
- cloudvolume/scheduler.py
- test/test_cloudvolume.py
`cv.unique` allows you to query arbitrarily large bounding boxes and extracts the unique labels in an online fashion to avoid excessive memory consumption. 
I also exploit the cseg and compresso formats so that the extraction can occur after only the first stage of decompression for additional speed.
> feat: add cv.unique

- cloudvolume/datasource/graphene/mesh/sharded.py
I discovered trying to work with a dataset with a floating point resolution that the draco mesh deduplication wasn't working correctly with graphene sharded.. i tracked the problem to this line, where casting the chunksize to integers caused the chunk boundary position prediction to accumulate error over many boundaries.... leading to incorrect detection of chunk boundaries and therefore improper stitching.
>  unnecessary integer casting for floating  chunk size

- cloudvolume/datasource/precomputed/skeleton/unsharded.py
A quick fix to respect compression settings when uploading skeletons.
I do replicate this logic from `get()`:
```python
compress = self.config.compress 
if compress is None:
compress = True
```
Is this logic encapsulated somewhere else in cloud-volume? It seems like it should probably not be replicated. (Perhaps this could be done by making config.compress a property?)
> Respect compression settings for skeleton uploads.

- README.md
- cloudvolume/chunks.py
- cloudvolume/datasource/precomputed/common.py
- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/image/rx.py
- cloudvolume/datasource/precomputed/sharding.py
- cloudvolume/frontends/graphene.py
- cloudvolume/frontends/precomputed.py
- test/test_cloudvolume.py
Download image files without rendering into a numpy array.
```
a_dict = cv.image.download_files(bbox, mip, decompress=True)
```
This could be useful for creating larger shard files in Igneous as it helps reduce memory pressure substantially.
> feat: cv.image.download_files

- README.md
- cloudvolume/__init__.py
- cloudvolume/datasource/boss/image.py
- cloudvolume/datasource/n5/__init__.py
- cloudvolume/datasource/n5/image.py
- cloudvolume/datasource/n5/metadata.py
- cloudvolume/paths.py
This PR adds read support for the `n5://` format: https://github.com/saalfeldlab/n5/
The way neuroglancer implements N5 appears to be somewhat different from the [specification](https://github.com/google/neuroglancer/tree/c3c8af92cf539773e3ffdcb39d1268a0e0c54a6d/src/neuroglancer/datasource/n5) and had to be reverse engineered. 
The way it seems to be really working is there is a root `attributes.json` file that gives a listing of the resolution and the scales. Then each scale is listed as `s$MIP` and has its own `attributes.json` file which describes the data type, chunk size, compression type, and dimensions.
We support all compression types via cloudfiles except lz4. Only mode 0 datasets are currently supported.
> feat: n5 image reading plugin

- README.md
- cloudvolume/chunks.py
- cloudvolume/datasource/precomputed/common.py
- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/image/tx.py
- cloudvolume/datasource/precomputed/metadata.py
- requirements.txt
- test/test_cloudvolume.py
This PR adds experimental support for the experimental [zfpc](https://github.com/seung-lab/zfpc) zfp container format. i.e. `"encoding": "zfpc"` in the info file.
This will allow for maximum compression of zfpc streams and defines new fields for Precomputed info file scales:
`zfpc_rate`, `zfpc_precision`, `zfpc_tolerance`, `zfpc_correlated_dims`
You must specify one or none of rate, precision, and tolerance (tolerance and rate are probably going to be the most preferred). `zfpc_correlated_dims` is a list of 4 booleans, where true means that axis index's data is correlated with other true dimensions.
For definitions of rate, tolerance, and precision, consult zfp documentation: https://zfp.readthedocs.io/en/latest/modes.html
For more information on zfpc and the correlated_dims parameter, …
> feat: add experimental zfpc codec to CloudVolume

- cloudvolume/skeleton.py
Running `Skeleton.simple_merge(skels)` fails if any of the skeletons are empty, since the length of dimension 1 is set to 0. This change simply reshapes the empty arrays to the correct shape to correct for this.
> Reshape empty arrays to allow concatenation of empty skeletons

- cloudvolume/datasource/precomputed/spatial_index.py
Improves run time of inserts to mysql. Took 3h35m to upload 193M rows with these improvements. 
Note: Must use SSD not HDD for CloudSQL. 
sqlite will also benefit from these improvements.
> perf(spatial_index): threaded, batched, and robust insert to mysql

- cloudvolume/datasource/precomputed/image/__init__.py
Secrets were not being passed to `tx.upload` on precomputed volumes.
I hit this as part of an experiment use cloud-files for https uploads (which will be a different PR). I found that info files, etc, were being created but the actual image data uploads were missing credentials.
> Pass secrets in PrecomputedImageSource.upload

- cloudvolume/datasource/graphene/mesh/unsharded.py
If a user is asking for a bounding box, then we need to force the server to use level 2 meshes, as the high level meshes will intersect with the bounding box and return a larger mesh than is desirable.
> force level2 if bounding box

- cloudvolume/datasource/precomputed/metadata.py
- cloudvolume/frontends/precomputed.py
Prints a yellow warning in the terminal if the currently selected scale key contains the string 'placeholder'.
> feat: add warning for placeholder mips

- cloudvolume/datasource/precomputed/image/rx.py
- cloudvolume/datasource/precomputed/metadata.py
- cloudvolume/lib.py
ROI format:
Added as key "rois" to the mip 0 scale in the info file.
List of lists of 6 integers [ xstart, ystart, zstart, xend, yend, zend ] specified in voxels at that scale.
> feat+perf: use precomputed ROIs to improve performance on empty regions

- README.md
- cloudvolume/cacheservice.py
- cloudvolume/cloudvolume.py
- cloudvolume/datasource/boss/__init__.py
- cloudvolume/datasource/graphene/__init__.py
- cloudvolume/datasource/n5/__init__.py
- cloudvolume/datasource/precomputed/__init__.py
- cloudvolume/datasource/precomputed/image/rx.py
- cloudvolume/datasource/precomputed/image/tx.py
- requirements.txt
Adds `CloudVolume(..., cache_locking=True)` flag (true by default). 
This starts using the new CloudFiles inter-process locking mechanism which uses `fasteners` to create locking files for local cache access but not for `file://` access generally.
This may have some performance implications, but can be switched off. It's only enabled for cache because otherwise the number of lock files will grow without bound. Caches get cleared periodically.
> feat: add cache multi-processing locking feature

- cloudvolume/datasource/precomputed/image/tx.py
- requirements.txt
Use a bulk encoding technique for transforming Fortran order image arrays into chunked fortran order byte objects. This uses more memory but is faster. We only use this new technique when the input image is appropriate and there is available RAM as measured by `psutil.virtual_memory().available`
> perf: accelerate raw encoding speed for f order images w/o compression

- README.md
- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/image/common.py
- cloudvolume/datasource/precomputed/image/xfer.py
- cloudvolume/datasource/precomputed/sharding.py
- cloudvolume/frontends/precomputed.py
- cloudvolume/types.py
- requirements.txt
- test/test_cloudvolume.py
Adds:
- unsharded->unsharded transcoding (transfer_to pre-existed)
- shard->shard + transcoding
- any -> unsharded + transcoding
- Anonymous memory based cutouts via cv.image.memory_cutout
Not covered:
- unsharded -> sharded (but it is in Igneous), it probably wouldn't be too much work but requires importing logic from igneous
> feat: shard->shard transfers, memory cutout, transcoding images

- cloudvolume/datasource/graphene/mesh/__init__.py
- cloudvolume/datasource/precomputed/__init__.py
- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/mesh/__init__.py
- cloudvolume/datasource/precomputed/mesh/metadata.py
- cloudvolume/datasource/precomputed/mesh/unsharded.py
- cloudvolume/datasource/precomputed/sharding.py
- cloudvolume/datasource/precomputed/skeleton/__init__.py
- cloudvolume/datasource/precomputed/skeleton/metadata.py
- cloudvolume/datasource/precomputed/skeleton/sharded.py
- cloudvolume/datasource/precomputed/skeleton/unsharded.py
- test/test_sharding.py
Adds logic for doing simple shard uploads for skeletons and adds logic for adding sharding specifications for images, meshes, and skeletons.
The shard specification logic is imported from Igneous.
```
N = 10000000
cv.image.to_sharded()
cv.mesh.to_sharded(num_labels=N)
cv.skeleton.to_sharded(num_labels=N)
cv.commit_info()
```
> feat: add skeleton sharded uploads

- cloudvolume/lib.py
This puts the docstring for Bbox in the right place so IDEs can display it, and adds a basic example
Before:
After:
> Fix Bbox docstring, add example

- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/metadata.py
- cloudvolume/frontends/precomputed.py
- cloudvolume/lib.py
- test/test_cloudvolume.py
- test/test_lib.py
This PR adds `unit='vx'` as a parameter to the Bbox class.
Supported units: vx (voxels), pm (picometers), nm (nanometers), um (micrometers), ...etc
The default unit Neuroglancer works in is nanometers so nm is the default assumption when physical units are used. vx is the default unit for Bbox.
```python
from cloudvolume import Bbox
Bbox([0,0,0], [1,1,1], unit='vx')
Bbox([0,0,0], [1,1,1], unit='nm')
Bbox([0,0,0], [1,1,1], unit='um')
bbox = Bbox.from_delta([106820, 84304, 21360], 512) # units "vx" by default
print(bbox)
>>> Bbox([106820, 84304, 21360],[107332, 84816, 21872], dtype=np.int32, unit='vx')
physical_bbox = bbox.convert_units("nm", resolution=[8,8,40], resolution_units="nm") 
print(physical_bbox)
>>> Bbox([854560, 674432, 854400],[858656, 678528, 874880], dtype=np.int64, …
```
> feat: Add "unit" to Bbox + accept physical Bbox in CV image functions

- cloudvolume/chunks.py
On Python versions <3.9, the first argument must be a list. Later versions of Python automatically coerce the arguments to work, but this maintains compatibility with old versions of python.
Fixes #622 .
> Fix Callable type annotation

- cloudvolume/lib.py
- setup.py
This is meant to fix two issues with lib.save_image:
1. The function requires the pillow library, but it's not included in requirements.txt.
2. There's a check if the image is np.bool that throws an error with the latest versions of numpy (I think the [np.bool alias expired with 1.24](https://numpy.org/doc/stable/release/1.24.0-notes.html)), causing an error when writing any dtype other than uint8.
> Fixes for lib.save_image

- README.md
- cloudvolume/chunks.py
- cloudvolume/cloudvolume.py
- cloudvolume/datasource/precomputed/__init__.py
- cloudvolume/datasource/precomputed/image/__init__.py
- cloudvolume/datasource/precomputed/image/rx.py
- cloudvolume/datasource/precomputed/image/tx.py
- cloudvolume/lru.py
- cloudvolume/paths.py
- test/test_cloudvolume.py
- test/test_dask.py
- test/test_lru.py
This PR adds the `lru_encoding` flag to CloudVolume at the top level. This allows you to choose the image encoding type of the LRU. This can be useful for either conserving additional space by choosing a higher compression type or for accelerating chunk reuse by selecting e.g. `raw` at the expense of more memory.
There may even be times when you can pick a faster and smaller compression type for certain queries.
The default value for `lru_encoding` is `"same"` which is whatever the current mip level's encoding is.
This change also makes parallel download compatible with non-raw LRU at the expense of additional encoding time.
> feat+perf: allow specifying LRU encoding type

- cloudvolume/lib.py
When the input to Bbox.create is a plain list or tuple of 6 integers, use Bbox.from_list instead of from_slices for more intuitive handling.
This makes it easier to create a bounding box from coordinates in the format [x_min, y_min, z_min, x_max, y_max, z_max].
> feat(bbox): handle plain lists of 6 ints in Bbox.create
