.travis.yml
cloudvolume/cloudvolume.py
cloudvolume/connectionpools.py
cloudvolume/lib.py
cloudvolume/secrets.py
cloudvolume/storage.py
cloudvolume/threaded_queue.py
requirements.txt
setup.cfg
test/test_connectionpools.py
test/test_storage.py
test/test_threadedqueue.py

Required changing out boto for boto3

feat: python3 support

---

test/layer_harness.py
test/test_storage.py

test: deconflict parallel storage tests

---

.travis.yml
cloudvolume/__init__.py
cloudvolume/cloudvolume.py
cloudvolume/connectionpools.py
cloudvolume/secrets.py
cloudvolume/storage.py
test/layer_harness.py
test/test_cloudvolume.py
test/test_provenance.py

Reading a JSON file but not encoding it as utf-8 means it remains
a bytes object.

fix: python3 compatibility

---

README.md
cloudvolume/cloudvolume.py
cloudvolume/storage.py
test/test_cloudvolume.py

Enables `vol.exists( Bbox )` or `vol.exists( np.s_[....] )`
Returns `{ filename: True, filename2: False }`
Resolves #8

feat: CloudVolume.exists

---

cloudvolume/cloudvolume.py
cloudvolume/lib.py
test/test_cloudvolume.py

Resolves #28 
Add support for things like:
CloudVolume('file:///usr/home/username/BUCKET/DATASET/LAYER/')

feat: add support for intermediate paths in URIs

---

cloudvolume/cloudvolume.py
requirements.txt
test/test_storage.py

This will prevent people from becoming frustrated while writing
provenance files which could discourage adoption.
http://json5.org/
Also changes some warnings to be yellow.
In response to #39

feat: provenance files are now decoded with the json5 module

---

cloudvolume/cloudvolume.py
cloudvolume/lib.py
cloudvolume/storage.py
test/test_cloudvolume.py
test/test_lib.py
test/test_storage.py

This required refactoring the path extraction logic out of
CloudVolume and Storage.

feat: CloudVolume supports intermediate paths

---

cloudvolume/threaded_queue.py

Optimize Sleep Patterns

---

cloudvolume/cloudvolume.py
cloudvolume/storage.py

Set cache-control to no-cache for info and provenance files
Resolves #31

feat: added cache-control options to Storage

---

cloudvolume/cloudvolume.py

Now prints when using vol.save_mesh(...):
Segment ID(s) $SEGIDS are missing corresponding mesh manifests.
Aborted.

feat: better error message for missing mesh manifests

---

cloudvolume/cloudvolume.py
cloudvolume/compression.py
cloudvolume/storage.py
test/test_storage.py

Now you can manually specify what compression algorithm to use
(or no algorithm). However, your choices are None and gzip
refactor: moved compression to compression.py from storage.py

feat: added compress option to CloudVolume

---

benchmark.py
create_test_volumes.py

Performance Benchmark

---

cloudvolume/cloudvolume.py
cloudvolume/storage.py
cloudvolume/threaded_queue.py

Downloading:
Blue = old algorithm on chunked data
Red = New algorithm on chunked data
Black = New Algorithm on single chunk download (but the old algorithm looks the same too)

Concurrent painting w/ Download (Save image size worth of memory)

---

cloudvolume/storage.py

Needed to use explicit pagination in order to completely list from Amazon.

fix: s3 listing was limited to 1000 files

---

README.md

Extracted bits of my runner to add into the docs, also changed some wording for easier reading. If it'd be helpful we could instead make an "examples" directory and I could make a friendlier version of my runner in there.

Changing the docs a bit

---

README.md
cloudvolume/__init__.py
cloudvolume/cacheservice.py
cloudvolume/cloudvolume.py
cloudvolume/lib.py
cloudvolume/storage.py
cloudvolume/volumecutout.py
test/test_cloudvolume.py

feat: preserve option for fush_cache + flush_cache_region

---

AUTHORS
ChangeLog
cloudvolume/__init__.py
cloudvolume/cacheservice.py
cloudvolume/cloudvolume.py
cloudvolume/lib.py
cloudvolume/storage.py
cloudvolume/txrx.py
test/test_cloudvolume.py

refactor: moved precomputed upload/download to txrx

feat: Added non-aligned chunk uploads.

---

cloudvolume/__init__.py
cloudvolume/skeletonservice.py
test/test_skeletons.py

feat: swc skeleton file generator
fix: get_point_cloud runtime error
http://research.mssm.edu/cnic/swc.html

feat: added radii and swc vertex attrs to skeleton binary format

---

ChangeLog
README.md
cloudvolume/cloudvolume.py
cloudvolume/lib.py
test/test_cloudvolume.py

feat: bbox_to_mip

---

cloudvolume/meshservice.py

* Huge speedup for `decode_mesh_buffer`
* Added fast-ish `mesh_to_ply` conversion

feat(meshservice): Faster mesh processing + PLY support

---

cloudvolume/cacheservice.py
cloudvolume/cloudvolume.py
cloudvolume/provenance.py
cloudvolume/txrx.py
test/test_cloudvolume.py

The provenance class derived from jsonschema objects did not pickle, preventing multiprocessing from operating correctly. This change preserves much of the same interface and validation characteristics of the DataLayerProvenance class while pickling correctly.

Easy External Multiprocessing

---

cloudvolume/cloudvolume.py
requirements.txt

fix: only reset connection pool when unpicking on a new PID

---

cloudvolume/lib.py
cloudvolume/storage.py
test/test_storage.py

feat: Storage works for any path, not just Neuroglancer paths

---

cloudvolume/lib.py
cloudvolume/storage.py

Bundles blob exists queries into Batch requests (only GCS).

feat(storage): Batch requests for GCS files_exist()

---

cloudvolume/__init__.py
cloudvolume/cloudvolume.py
cloudvolume/lib.py
test/test_cloudvolume.py
test/test_lib.py

Bbox Upgrades

---

ChangeLog
cloudvolume/connectionpools.py
cloudvolume/exceptions.py
cloudvolume/lib.py
cloudvolume/storage.py

fix: close requests streams 

---

cloudvolume/lib.py
cloudvolume/secrets.py

auto load the environment variable if there is no secret json files found.

[Feature] add a little bit comments; add support for environment variables

---

cloudvolume/secrets.py

@william-silversmith this is a simple feature, can we merge directly?

add support for default region

---

cloudvolume/cloudvolume.py
cloudvolume/lib.py
cloudvolume/secrets.py
test/test_cloudvolume.py
test/test_lib.py

- add from_numpy function to construct a volume; 
- remove unused imported packages and redefined functions

Add from_numpy Function to Automatically Construct a Precomputed Volume

---

cloudvolume/chunks.py
requirements.txt

This makes kempression work properly.

chore: fpzip 1.1.3 compatibility

---

cloudvolume/cloudvolume.py
test/test_cloudvolume.py

the usage of add_scale function is not correct.
also make the test creating multiple mip levels of the info.

fix from numpy function with multiple mip levels

---

cloudvolume/cloudvolume.py

- I missed the bool dtype
- the np.floating is the latest abstract floating point dtype. I got warning in python 3.6 if using np.float.

add boolean and use floating abstract dtype

---

cloudvolume/lib.py

the old version is broken for windows.

changing to an os independent character

---

cloudvolume/cloudvolume.py
cloudvolume/storage.py

@ranlu saw problems with provenance files dying due to 429s on GCP. In this PR we reduce the number of requests and also make the existence test more robust.

feat: more robust provenance refreshes

---

ChangeLog
cloudvolume/__init__.py
cloudvolume/lib.py

fix: select single channel in save_images

---

cloudvolume/chunks.py
test/test_chunks.py

Previously, color (RGB) jpeg simply did not work.

fix: color jpeg encoding support

---

cloudvolume/meshservicegraphene.py
requirements.txt

Adds DracoPy as a dependency. Will attempt to use DracoPy to decode a
fragment then fall back to the old decoder if that raises an error.

GrapheneMeshService able to decode draco meshes [for graphene branch]

---

cloudvolume/storage.py
test/test_storage.py

* Changes `delete_files` behavior similar to the `files_exist` methods.
* Adds support for GCS Batch Delete requests

feat: Support for GCS Batch Delete

---

cloudvolume/cloudvolume.py
cloudvolume/datasource/precomputed/skeleton.py
test/test_skeletons.py

Adds this operation by default to consolidate.

feat: add PrecomputedSkeleton.remove_disconnected_vertices

---

cloudvolume/server.py

Fix to make vol.viewer() functional again.

fix: correct ExtractedPath import for web server viewer

---

.travis.yml
requirements.txt
setup.py

chore: make pytest optional with [test] dependency

---

cloudvolume/datasource/graphene/metadata.py

Single line fix. Previous call didn't exist.

fix to_https_protocol call

---

cloudvolume/paths.py
test/test_paths.py

fix: allow ports in bucket paths

---

cloudvolume/frontends/graphene.py
test/test_graphene.py

should address #265 needs a better test, not sure best way to assume data @william-silversmith

adding fix for __getitem__ in graphene plus test

---

cloudvolume/datasource/precomputed/image/tx.py
cloudvolume/datasource/precomputed/mesh.py

fix: use OS+protocol aware join command for meshes and skeletons

---

cloudvolume/datasource/precomputed/skeleton/unsharded.py

fix: ensure the correct path separator is used for skeleton upload

---

cloudvolume/datasource/precomputed/mesh/__init__.py
cloudvolume/datasource/precomputed/mesh/metadata.py
cloudvolume/datasource/precomputed/mesh/unsharded.py

feat: create mesh metadata class
refactor: structure mesh datasources to accomodate sharded

feat: read mesh spatial index

---

cloudvolume/datasource/precomputed/sharding.py

fix: check to make sure there is a match in the minishard index

fix(ShardReader): only scan labels in minishard_index

---

cloudvolume/datasource/precomputed/image/__init__.py
cloudvolume/datasource/precomputed/image/tx.py
test/test_cloudvolume.py
test/test_storage.py

fix: EmptyVolumeException w/ non_aligned_writes

---

cloudvolume/datasource/precomputed/mesh/unsharded.py

Add missed import of CachedSpatialIndex in mesh/unshared.py.

Add CachedSpatialIndex to import

---

cloudvolume/frontends/graphene.py

Also switch to using HTTP headers for gzip

feat: use full binary endpoint for agglomeration

---

cloudvolume/datasource/precomputed/sharding.py
cloudvolume/lib.py
cloudvolume/storage/storage.py
test/test_skeletons.py

feat: add start and end to Storage.get_files
Resolves #326

feat: add ShardReader.list_labels

---

cloudvolume/datasource/precomputed/image/rx.py
cloudvolume/datasource/precomputed/sharding.py
cloudvolume/exceptions.py

fix: support fill_missing for sharded images

---

cloudvolume/datasource/graphene/mesh/sharded.py

fix: pass arguments to super more accurately

---

cloudvolume/cloudvolume.py
cloudvolume/datasource/graphene/__init__.py
cloudvolume/datasource/graphene/sharding.py
cloudvolume/datasource/precomputed/__init__.py

fix: use correct cache location for graphene

feat: add mesh_dir and skel_dir arguments to CloudVolume

---

cloudvolume/sharedmemory.py

Previously we were writing out real files full of zeros,
but a) that takes forever and b) modern OSes support sparse
files (i.e. gigabytes of zeros that take up only a few real bytes).
The following should take advantage of this functionality and be faster.
It should work on Python 2.7 Unix, and Python 3.5+ on Unix and Windows.
References:
https://stackoverflow.com/questions/8816059/create-file-of-particular-size-in-python
https://docs.python.org/3/library/os.html#os.ftruncate
https://docs.python.org/2/library/os.html#os.ftruncate
Hopefully the use of spare files will help prevent issues like one user experienced where an error ate up his hard drive's free space on Windows.
This issue might fix #222

perf: instant fs based shared memory files + use spare file capability

---

cloudvolume/datasource/graphene/metadata.py
cloudvolume/frontends/graphene.py

Range read request is needed to do meshing
Edit: This PR is reliant on this PR in the CG to be deployed: https://github.com/seung-lab/PyChunkedGraph/pull/198

Add range read request to graphene and new properties to graphene metadata

---

cloudvolume/lru.py
test/test_lru.py

test: add more chaotic test for LRU
Resolves #341

fix(lru): delete was not handling case where node is head or tail

---

cloudvolume/cacheservice.py
cloudvolume/datasource/precomputed/sharding.py
cloudvolume/lib.py
cloudvolume/scheduler.py
cloudvolume/storage/storage.py

Need to group the minishard requests more effectively.
@akhileshh needs this to make the graphene server more responsive.

perf: parallelized ShardReader.exists

---

cloudvolume/cacheservice.py
cloudvolume/datasource/graphene/mesh/sharded.py
cloudvolume/datasource/precomputed/image/rx.py
cloudvolume/datasource/precomputed/mesh/__init__.py
cloudvolume/datasource/precomputed/sharding.py
cloudvolume/datasource/precomputed/skeleton/sharded.py
cloudvolume/storage/__init__.py
test/test_skeletons.py

- adds green flag to ShardReader.
- Now the shard_index_cache is always indexed by path instead of just the shard name.
- get_data is now threaded
- adds progress argument

perf: threaded shard get_data

---

cloudvolume/datasource/graphene/mesh/unsharded.py

Add parameter that allows user to disable vertex deduplication

make vertex deduplication optional in vol.mesh.get()

---

cloudvolume/datasource/precomputed/image/__init__.py
cloudvolume/datasource/precomputed/metadata.py
cloudvolume/lib.py
test/test_cloudvolume.py

feat(PrecomputedImage): adds has_data(mip) call

---

cloudvolume/datasource/precomputed/image/__init__.py
cloudvolume/datasource/precomputed/image/rx.py
test/test_sharding.py

Enables writing single shards using the familiar upload syntax. Multiple shards will currently crash.

feat(PrecomputedImage): add make_shard function

---

cloudvolume/frontends/precomputed.py
cloudvolume/lib.py
test/test_lib.py

fix: special logic for handling slices

---

cloudvolume/cloudvolume.py
cloudvolume/datasource/graphene/__init__.py
cloudvolume/datasource/graphene/metadata.py
cloudvolume/datasource/precomputed/__init__.py
cloudvolume/frontends/graphene.py

@supersergiy something like this?
```
cv = CloudVolume('graphene://...', agglomerate=True)
img = cv[...]
```

feat: add agglomerate mode for graphene

---

cloudvolume/datasource/graphene/mesh/sharded.py

fix: incompatibility between inital and dynamic meshes

---

cloudvolume/datasource/graphene/mesh/sharded.py
cloudvolume/datasource/graphene/mesh/unsharded.py

redesign(graphene): use synthetic manifests for fetching meshes

---

cloudvolume/datasource/precomputed/image/rx.py
cloudvolume/frontends/graphene.py

fix(graphene): update leaves call for api v1

---

cloudvolume/datasource/graphene/mesh/unsharded.py

fix(graphene): dynamic mesh computed filename didn't account for layer

---

cloudvolume/frontends/graphene.py

fix(graphene): if timestamp is None, to_unix_time breaks

---

cloudvolume/paths.py
test/test_paths.py

Windows parsing was dropping the bucket name from the path.

fix(windows,paths): non-file windows parsing was broken

---

cloudvolume/datasource/precomputed/mesh/multilod.py

fix(sharded,mesh): pass progress to CloudFiles

---

cloudvolume/datasource/precomputed/__init__.py
cloudvolume/datasource/precomputed/metadata.py
cloudvolume/paths.py

fix(use_https): redirects respect the use_https flag

---

requirements.txt
setup.py

Manuel released new binaries for DracoPy on Windows so now
we can process meshes.

chore(Windows): install dracopy on windows

---

cloudvolume/chunks.py
requirements.txt

This update will streamline the compression phase logic, make the decompression order work as expected and also prevent compressing volumes that are not supported by the specification.

refactor(compressed_segmentation): use updated 2.0.0 package

---

cloudvolume/secrets.py

redesign: readonly environment

---

cloudvolume/datasource/precomputed/spatial_index.py
requirements.txt

Initial tests seem to shrink the share of compute for JSON parsing dramatically.

perf(spatial_index): replace orjson with pysimdjson and only parse keys

---

cloudvolume/datasource/precomputed/spatial_index.py
cloudvolume/lib.py

feat(spatial_index): create sqlite database from index

---

cloudvolume/chunks.py
cloudvolume/datasource/precomputed/image/rx.py
test/test_cloudvolume.py

Currently, only works for parallel=1

fix: background_color not applied when bounded=False, fill_missing=True

---

cloudvolume/scheduler.py
test/test_cloudvolume.py

Green threads were swallowing exceptions.

fix: raise errors from green threads

---

cloudvolume/frontends/graphene.py

feat(graphene): adds stop_layer to get_leaves for api v1

---

cloudvolume/frontends/graphene.py
test/test_graphene.py

feat(get_roots): avoid sending zeros, dupes, and root ids to server

---

cloudvolume/datasource/precomputed/skeleton/metadata.py

Updated for resolving key error in 'sharding'

Updated for resolving key error in 'sharding'

---

cloudvolume/datasource/precomputed/image/__init__.py
cloudvolume/datasource/precomputed/image/common.py
cloudvolume/datasource/precomputed/image/rx.py
cloudvolume/datasource/precomputed/image/tx.py
cloudvolume/lib.py
cloudvolume/scheduler.py
cloudvolume/sharedmemory.py
cloudvolume/storage/storage_interfaces.py
requirements.txt

- Consolidates progress bar
- Checks for errors at end
- Fixes segfault on MacOS
- Accepts iterators
- Fixes file lock synchronization issue on MacOS

fix: make parallel image IO more robust

---

requirements.txt

fixing recent jsonschema issue #501

pinning jsonschema<4.0

---

cloudvolume/cacheservice.py

fix: correct multi-level paths being cached on Windows

---

cloudvolume/frontends/graphene.py
cloudvolume/frontends/precomputed.py

Copies the feature from download_point to download.

feat: adds coord_resolution argument to cv.download

---

cloudvolume/chunks.py
test/test_chunks.py

feat: add png encode/decode to chunks.py

---

cloudvolume/datasource/precomputed/mesh/multilod.py

Fixes several issues with creating a stored model representation, reading and writing the manifest.

fix+feat: Multi-Resolution Mesh Encoding

---

README.md
cloudvolume/datasource/precomputed/image/__init__.py
cloudvolume/datasource/precomputed/metadata.py
cloudvolume/frontends/graphene.py
cloudvolume/frontends/precomputed.py
test/test_cloudvolume.py

feat+perf(download_points): parallel point fetching

---

README.md
cloudvolume/chunks.py
cloudvolume/datasource/precomputed/common.py
requirements.txt
test/test_chunks.py

Adding BETA support for the new crackle segmentation compression codec.
https://github.com/seung-lab/crackle
Please regard this new codec as BETA and subject to change, so don't use it for anything too serious yet. However, the codec has reached a stage of maturity where it could be useful.

feat: crackle segmentation compression codec (BETA!)

---

cloudvolume/cacheservice.py
cloudvolume/chunks.py
cloudvolume/cloudvolume.py
cloudvolume/datasource/boss/__init__.py
cloudvolume/datasource/graphene/__init__.py
cloudvolume/datasource/n5/__init__.py
cloudvolume/datasource/precomputed/__init__.py
cloudvolume/datasource/precomputed/image/__init__.py
cloudvolume/datasource/precomputed/image/rx.py
cloudvolume/datasource/precomputed/image/tx.py
cloudvolume/mesh.py
requirements.txt
test/test_meshing.py

Refactors the image shard generation code to enable also extracting filenames.

feat+refactor: add shard filename function for images

---

cloudvolume/datasource/precomputed/image/rx.py
cloudvolume/lru.py

fix: prevent race condition on LRU lock

---

cloudvolume/cloudvolume.py

Skeleton typo

---

cloudvolume/skeleton.py

This makes more brittle SWC parsers happy.

fix: renumber SWC rows
